#!/usr/bin/env python3
"""Create current.json sidebar translation files from existing _category_.json files.

Docusaurus uses _category_.json only for autogenerated sidebars.
Since this project uses a manual sidebar (sidebars.ts), category label
translations must go in i18n/{locale}/docusaurus-plugin-content-docs/current.json.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
I18N = ROOT / "i18n"

# Mapping from _category_.json paths to current.json keys
CATEGORY_MAP = {
    "about/_category_.json": "sidebar.helpSidebar.category.About Outline",
    "client/_category_.json": "sidebar.helpSidebar.category.Outline Client",
    "client/getting-started/_category_.json": "sidebar.helpSidebar.category.Getting Started",
    "client/troubleshooting/_category_.json": "sidebar.helpSidebar.category.client-troubleshooting",
    "manager/_category_.json": "sidebar.helpSidebar.category.Outline Manager",
    "manager/server-setup/_category_.json": "sidebar.helpSidebar.category.Server Setup",
    "manager/server-management/_category_.json": "sidebar.helpSidebar.category.Server Management",
    "manager/troubleshooting/_category_.json": "sidebar.helpSidebar.category.manager-troubleshooting",
    "developers/_category_.json": "sidebar.helpSidebar.category.For Developers",
}

# English defaults (fallback if no translation exists)
ENGLISH_DEFAULTS = {
    "sidebar.helpSidebar.category.About Outline": "About Outline",
    "sidebar.helpSidebar.category.Outline Client": "Outline Client",
    "sidebar.helpSidebar.category.Getting Started": "Getting Started",
    "sidebar.helpSidebar.category.client-troubleshooting": "Troubleshooting",
    "sidebar.helpSidebar.category.Outline Manager": "Outline Manager",
    "sidebar.helpSidebar.category.Server Setup": "Server Setup",
    "sidebar.helpSidebar.category.Server Management": "Server Management",
    "sidebar.helpSidebar.category.manager-troubleshooting": "Troubleshooting",
    "sidebar.helpSidebar.category.For Developers": "For Developers",
}

DESCRIPTIONS = {
    "sidebar.helpSidebar.category.About Outline": "The label for category 'About Outline' in sidebar 'helpSidebar'",
    "sidebar.helpSidebar.category.Outline Client": "The label for category 'Outline Client' in sidebar 'helpSidebar'",
    "sidebar.helpSidebar.category.Getting Started": "The label for category 'Getting Started' in sidebar 'helpSidebar'",
    "sidebar.helpSidebar.category.client-troubleshooting": "The label for category 'Troubleshooting' in sidebar 'helpSidebar'",
    "sidebar.helpSidebar.category.Outline Manager": "The label for category 'Outline Manager' in sidebar 'helpSidebar'",
    "sidebar.helpSidebar.category.Server Setup": "The label for category 'Server Setup' in sidebar 'helpSidebar'",
    "sidebar.helpSidebar.category.Server Management": "The label for category 'Server Management' in sidebar 'helpSidebar'",
    "sidebar.helpSidebar.category.manager-troubleshooting": "The label for category 'Troubleshooting' in sidebar 'helpSidebar'",
    "sidebar.helpSidebar.category.For Developers": "The label for category 'For Developers' in sidebar 'helpSidebar'",
}

total_created = 0
total_missing = 0

for locale_dir in sorted(I18N.iterdir()):
    if not locale_dir.is_dir():
        continue
    # Skip partial-translations and non-locale dirs
    docs_dir = locale_dir / "docusaurus-plugin-content-docs" / "current"
    if not docs_dir.exists():
        continue

    locale = locale_dir.name
    current_json_path = locale_dir / "docusaurus-plugin-content-docs" / "current.json"

    # Build translations from _category_.json files
    translations = {}
    missing = []

    for cat_path, json_key in CATEGORY_MAP.items():
        cat_file = docs_dir / cat_path
        if cat_file.exists():
            try:
                data = json.loads(cat_file.read_text("utf-8"))
                label = data.get("label", "")
                if label:
                    translations[json_key] = {
                        "message": label,
                        "description": DESCRIPTIONS[json_key],
                    }
                else:
                    missing.append(json_key)
            except (json.JSONDecodeError, KeyError):
                missing.append(json_key)
        else:
            missing.append(json_key)

    # Fill in any missing translations with English defaults
    for key in CATEGORY_MAP.values():
        if key not in translations:
            translations[key] = {
                "message": ENGLISH_DEFAULTS[key],
                "description": DESCRIPTIONS[key],
            }

    # Add version label
    result = {"version.label": {"message": "Next", "description": "The label for version current"}}
    # Add in sidebar order
    for key in [
        "sidebar.helpSidebar.category.About Outline",
        "sidebar.helpSidebar.category.Outline Client",
        "sidebar.helpSidebar.category.Getting Started",
        "sidebar.helpSidebar.category.client-troubleshooting",
        "sidebar.helpSidebar.category.Outline Manager",
        "sidebar.helpSidebar.category.Server Setup",
        "sidebar.helpSidebar.category.Server Management",
        "sidebar.helpSidebar.category.manager-troubleshooting",
        "sidebar.helpSidebar.category.For Developers",
    ]:
        result[key] = translations[key]

    # Write current.json
    current_json_path.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", "utf-8")

    if missing:
        print(f"  CREATED {locale}/current.json (missing: {len(missing)} categories used English)")
        total_missing += len(missing)
    else:
        print(f"  CREATED {locale}/current.json (all 9 categories translated)")
    total_created += 1

print(f"\nDone: {total_created} current.json files created, {total_missing} missing translations (used English defaults)")
